### ISSUE TITLE
open drain parameters are inverted

### ISSUE THREAD

**Issue by ed-xmos** [kadamski/i2c-gpio-param#5]
The sda_od and scl_od parameters seem inverted.
Tested on Pi3 Jessie 4.4.26-v7+
For example:

echo 5 2 3 5 50 1 1 0 > /sys/class/i2c-gpio/add_bus 

results in contention on the I2C during ACK. This suggests the pi host is driving high rather than releasing the pin.

echo 5 2 3 5 50 0 0 0 > /sys/class/i2c-gpio/add_bus 

works well and both ACK is seen correctly and clock stretching works perfectly (they work in open drain mode), even though sda_od and scl_od have been set to zero.. 

It looks like these params are being passed directly through to i2c-gpio.c so this is not a code issue, rather something for the readme.md file

**Comment by kadamski** [comment]
Haven't looked into that code for years, I'm surprised it even still works :) Looking into that again, I don't think there is any error or anything is inverted here. What this "scl_od" and "sda_od" mean is that the GPIO you are going to use is configured as open drain. I don't think RPI can do that.

When GPIO is in open drain mode, I2C can work exactly as it normally should - you set your GPIO state to 1 or 0, depending on what you want. As often this mode is not supported by GPIO hardware, there is a way i2c-gpio module is using to simulate this functionality. In that case, when you want to write 1, the gpio is set to input mode (usually meaning hi-z), allowing the external pull-up to set bus to high, in case of 0, it is set to output and value to 0, driving bus actively low.

Compare i2c_gpio_setsda_dir (used when OD is disabled):
http://elixir.free-electrons.com/linux/latest/source/drivers/i2c/busses/i2c-gpio.c#L28

to i2c_gpio_setsda_val (used when OD is enabled):
http://elixir.free-electrons.com/linux/latest/source/drivers/i2c/busses/i2c-gpio.c#L43

So, since your GPIOs are not configured to open drain mode, the bus does not work when you claim it is. It can only work if configured to disable OD mode. That being said, I admit the documentation could be more clear about that.

Does this sound reasonable to you?

**Comment by ed-xmos** [comment]
Thanks for the quick response! Sounds reasonable to me. Essentially then, it's an issue with limitations of the BCM2837 not supporting true open drain mode. I'll make a pull request for README.md

**Comment by ed-xmos** [comment]
Done - https://github.com/ed-xmos/i2c-gpio-param/tree/patch-1
